title: Knowlton Lab
author: Nick Knowlton
email: n.knowlton@auckland.ac.nz
description: >-
  Knowlton Lab at the University of Auckland and Massey University, focused on
  applied statistics, machine learning, and translational biomedical research.
baseurl: ""
url: "https://knowlton.co.nz"
show_excerpts: false

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
  - research.md
  - students.md
  - teaching.md

minima:
  skin: dark
  social_links:
    github: nknowlton
    linkedin: nsknowlton
